AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets and IAM role for 8 ArtChain microservices

Resources:
  # ---------- COMMON SECRET (accessible by all services) ----------
  ArtChainCommonSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ArtChainCommonSecret
      Description: Shared secrets for all services
      SecretString: !Sub |
        {
          "PORT": "8080",
          "NODE_ENV": "production",
          "MONGO_URI": "mongodb+srv://admin:password@cluster.mongodb.net"
        }

  # ---------- SERVICE SPECIFIC SECRETS ----------
  ArtChainService1Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ArtChainService1Secret
      Description: Service 1 specific secret
      SecretString: '{"API_KEY":"service1_dummy_key"}'

  ArtChainService2Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ArtChainService2Secret
      Description: Service 2 specific secret
      SecretString: '{"API_KEY":"service2_dummy_key"}'

  ArtChainService3Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ArtChainService3Secret
      Description: Service 3 specific secret
      SecretString: '{"API_KEY":"service3_dummy_key"}'

  ArtChainService4Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ArtChainService4Secret
      Description: Service 4 specific secret
      SecretString: '{"API_KEY":"service4_dummy_key"}'

  ArtChainService5Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ArtChainService5Secret
      Description: Service 5 specific secret
      SecretString: '{"API_KEY":"service5_dummy_key"}'

  ArtChainService6Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ArtChainService6Secret
      Description: Service 6 specific secret
      SecretString: '{"API_KEY":"service6_dummy_key"}'

  ArtChainService7Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ArtChainService7Secret
      Description: Service 7 specific secret
      SecretString: '{"API_KEY":"service7_dummy_key"}'

  ArtChainService8Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ArtChainService8Secret
      Description: Service 8 specific secret
      SecretString: '{"API_KEY":"service8_dummy_key"}'

  # ---------- SINGLE IAM ROLE FOR ALL SERVICES ----------
  AllServicesRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AllServicesRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllServicesSecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref ArtChainCommonSecret
                  - !Ref ArtChainService1Secret
                  - !Ref ArtChainService2Secret
                  - !Ref ArtChainService3Secret
                  - !Ref ArtChainService4Secret
                  - !Ref ArtChainService5Secret
                  - !Ref ArtChainService6Secret
                  - !Ref ArtChainService7Secret
                  - !Ref ArtChainService8Secret

Outputs:
  CommonSecretName:
    Value: !Ref ArtChainCommonSecret
    Description: Common secret shared by all services

  Service1SecretName:
    Value: !Ref ArtChainService1Secret
    Description: Service 1 secret

  Service2SecretName:
    Value: !Ref ArtChainService2Secret
    Description: Service 2 secret

  Service3SecretName:
    Value: !Ref ArtChainService3Secret
    Description: Service 3 secret

  Service4SecretName:
    Value: !Ref ArtChainService4Secret
    Description: Service 4 secret

  Service5SecretName:
    Value: !Ref ArtChainService5Secret
    Description: Service 5 secret

  Service6SecretName:
    Value: !Ref ArtChainService6Secret
    Description: Service 6 secret

  Service7SecretName:
    Value: !Ref ArtChainService7Secret
    Description: Service 7 secret

  Service8SecretName:
    Value: !Ref ArtChainService8Secret
    Description: Service 8 secret
