export const ROUTES = {
  AUTH: {
    LOGOUT: "/api/v1/auth/logout",
  },
  USER: {
    SUPPORT: "/api/v1/user/support/:userId",
    UN_SUPPORT: "/api/v1/user/un-support/:userId",
    REMOVE_SUPPORTER: "/api/v1/user/remove/:supporterId",
    ARTIST_REQUEST: "/api/v1/user/artist-request",
    ARTIST_REQUEST_STATUS: "/api/v1/user/artist-request/status",
    CHANGE_PASSWORD: "/api/v1/user/change-password",
    CHANGE_EMAIL: "/api/v1/user/change-email",
    VERIFY_EMAIL_TOKEN: "/api/v1/user/verify-email-token",
    DEACTIVATE: "/api/v1/user/deactivate",
    PROFILE: "/api/v1/user/profile",
    PROFILE_BY_USERNAME: "/api/v1/user/profile/:username",
    SUPPORTERS: "/api/v1/user/:id/supporters",
    SUPPORTING: "/api/v1/user/:id/supporting",
    REPORT: "/api/v1/user/report",
  },
  NOTIFICATIONS: {
    BASE: "/api/v1/notifications",
    MARK_ALL_READ: "/api/v1/notifications/mark-all-read",
  },
  ART: {
    BASE: "/api/v1/art",
    BY_NAME: "/api/v1/art/by-name/:artname",
    BY_USER: "/api/v1/art/user/:userId",
    COMMENT: "/api/v1/art/comment",
    COMMENTS: "/api/v1/art/comments",
    COMMENTS_BY_ID: "/api/v1/art/comments/:id",
    COMMENTS_BY_POST_ID: "/api/v1/art/comments/:postId",
    LIKE: "/api/v1/art/like",
    DISLIKE: "/api/v1/art/disLike",
    UNLIKE: "/api/v1/art/unlike",
    LIKES_BY_POST_ID: "/api/v1/art/likes/:postId",
    FAVORITE: "/api/v1/art/favorite",
    UNFAVORITE: "/api/v1/art/unfavorite",
    FAVORITES_BY_POST_ID: "/api/v1/art/favorites/:postId",
    FAVORITES_BY_USER: "/api/v1/art/favorites/user/:userId",
    CATEGORY: "/api/v1/art/category",
    AUCTIONS: "/api/v1/art/auctions",
    AUCTION_BY_ID: "/api/v1/art/auctions/:id",
    BIDS: "/api/v1/art/bids",
    BIDS_BY_AUCTION: "/api/v1/art/bids/:auctionId",
  },
  UPLOAD: {
    BASE: "/api/v1/upload",
    ART: "/api/v1/upload/art",
    DELETE: "/api/v1/upload/delete",
  },
  WALLET: {
    BASE: "/api/v1/wallet",
    DETAILS: "/api/v1/wallet/details",
    CREATE_CHECKOUT_SESSION: "/api/v1/wallet/stripe/create-checkout-session",
    GET_TRANSACTIONS: "/api/v1/wallet/get-transactions",
    CREATE_TRANSACTIONS: "/api/v1/wallet/create-transactions",
    STATS_CHART: "/api/v1/wallet/stats/chart",
    
    // Withdrawal routes
    WITHDRAWAL_CREATE: "/api/v1/wallet/withdrawal/create",
    WITHDRAWAL_REQUESTS: "/api/v1/wallet/withdrawal/requests",
    WITHDRAWAL_REQUEST_BY_ID: "/api/v1/wallet/withdrawal/requests/:id",
    
    // Admin withdrawal routes
    ADMIN_WITHDRAWAL_REQUESTS: "/api/v1/wallet/admin/withdrawal/requests",
    ADMIN_WITHDRAWAL_UPDATE_STATUS: "/api/v1/wallet/admin/withdrawal/requests/:withdrawalId/status",
  },
  CHAT: {
    PRIVATE: "/api/v1/chat/conversation/private",
    RECENT: "/api/v1/chat/conversation/recent",
    MESSAGE: "/api/v1/chat/message/:conversationId",
    GROUP: "/api/v1/chat/conversation/group",
    GROUP_BY_ID: "/api/v1/chat/conversation/group/:conversationId",
    MEMBERS: "/api/v1/chat/conversation/:conversationId/members",
    MEMBER: "/api/v1/chat/conversation/:conversationId/member/:userId",
    ADMIN: "/api/v1/chat/conversation/:conversationId/admin/:userId",
    DELETE_MESSAGE: "/api/v1/chat/message/:messageId",
  },
  AI: {
    GENERATE: "/api/v1/art/ai/generate",
    QUOTA: "/api/v1/art/ai/quota",
    GENERATIONS: "/api/v1/art/ai/generations",
    CONFIG: "/api/v1/art/ai/config",
    ANALYTICS: "/api/v1/art/ai/analytics",
    TEST_PROVIDER: "/api/v1/art/ai/test-provider",
    DELETE_GENERATION: "/api/v1/art/ai/generations/:id",
  },
  ADMIN: {
    DASHBOARD: "/api/v1/admin/dashboard",
    USERS: "/api/v1/admin/users",
    REVENUE: "/api/v1/admin/revenue-stats",
    WALLETS: "/api/v1/wallet/admin/wallets",
    SEARCH_WALLETS: "/api/v1/wallet/admin/wallets/search",
    UPDATE_STATUS: "/api/v1/wallet/admin/wallets/:walletId/status",
    GET_USER_TRANSACTIONS: "/api/v1/wallet/admin/wallets/:walletId/transactions",
    REVENUE_STATS: "/api/v1/wallet/admin/revenue-stats",
  },
};
