export const NAMES = [
  // Spanish
  'Carlos Mendez',
  'Sofia Rodriguez',
  'Miguel Angel',
  'Lucia Fernandez',
  'Diego Rivera',
  'Isabella Torres',
  'Pedro Martinez',
  'Maria Gonzalez',
  'Valentina Diaz',
  'Camila Rojas',
  'Andres Torres',
  'Daniela Sanchez',
  'Jorge Sanchez',
  'Clara Moreno',
  'Pedro Gonzalez',
  'Sofia Rojas',
  'Lucia Torres',
  'Diego Sanchez',
  'Carlos Rojas',
  'Sofia Fernandez',

  // Korean
  'Jin Soo Kim',
  'Hana Park',
  'Min Ji Lee',
  'Jung Hoon Choi',
  'Jin Woo Park',
  'Seok Jin Lee',
  'Min Seo Kim',
  'Eun Ji Park',
  'Joon Ho Kim',
  'Jung Min Choi',
  'Hye Jin Park',
  'Seung Min Kim',
  'Hye Sun Park',
  'Isabella Kim',
  'Jung Woo Park',
  'Diego Kim',
  'Min Seo Lee',
  'Seok Woo Choi',

  // Indian / Malayalam
  'Arjun Nair',
  'Anjali Menon',
  'Vineeth Ramesh',
  'Priya Pillai',
  'Siddharth Kumar',
  'Meera Suresh',
  'Rohan Varma',
  'Lakshmi Nair',
  'Karthik Raj',
  'Divya Mohan',
  'Aarav Iyer',
  'Nithya Krishnan',
  'Aditya Menon',
  'Revathi Nair',
  'Krishna Prasad',
  'Anjana Ramesh',
  'Rahul Varma',
  'Sneha Pillai',
  'Vishnu Kumar',
  'Parvathi Suresh',

  // Anime characters
  'Naruto Uzumaki',
  'Sasuke Uchiha',
  'Sakura Haruno',
  'Kakashi Hatake',
  'Goku',
  'Vegeta',
  'Bulma',
  'Piccolo',
  'Luffy',
  'Zoro',
  'Nami',
  'Sanji',
  'Light Yagami',
  'L Lawliet',
  'Mikasa Ackerman',
  'Eren Yeager',
  'Levi Ackerman',
  'Gon Freecss',
  'Killua Zoldyck',
  'Ichigo Kurosaki',
  'Rukia Kuchiki',

  // Chinese
  'Zhuge Liang',
  'Wu Zetian',
  'Cao Cao',
  'Yang Guifei',
  'Sima Yi',
  'Hua Mulan',
  'Lin Zexu',
  'Cai Wenji',
  'Yue Fei',
  'Ban Zhao',
  'Sun Tzu',
  'Xi Shi',
  'Qin Shi Huang',
  'Diaochan',
  'Zhuangzi',
  'Li Qingzhao',

  // Vietnamese
  'Tran Hung Dao',
  'Trung Trac',
  'Ngo Quyen',
  'Trung Nhi',
  'Nguyen Hue',
  'Ba Trieu',
  'Le Thanh Tong',
  'Bui Thi Xuan',
  'Dinh Bo Linh',
  'Doan Thi Diem',
  'Gia Long',
  'Ho Xuan Huong',
  'Minh Mang',
  'Nguyen Thi Dinh',
  'Lac Long Quan',
  'Au Co',

  // Thai
  'Narai Maharat',
  'Suriyothai',
  'Taksin Borom',
  'Thepsatri',
  'Chulalongkorn',
  'Chamadevi',
  'Sunthorn Phu',
  'Kunying Mo',
  'Sriprat Chat',
  'Sarocha Burin',
  'Thanakorn Sir',
  'Patcharaporn',
  'Kittisak Wong',
  'Nuttanicha',
  'Worawat Chat',
  'Malee Panat',

  // Indonesian
  'Gajah Mada',
  'Cut Nyak Dhien',
  'Hayam Wuruk',
  'Kartini',
  'Diponegoro',
  'Martha Tiahahu',
  'Suryakancana',
  'Tribhuwana Tunggadewi',
  'Joko Widodo',
  'Megawati Sukarnoputri',
  'Bambang Pamungkas',
  'Anggun Cipta Sasmi',
  'Prabowo Subianto',
  'Susi Pudjiastuti',
  'Indra Wijaya',
  'Dewi Sartika',
];
