export enum COMMISSION_MESSAGES {
  REQUESTER_AND_ARTIST_REQUIRED = 'Requester and Artist IDs are required',
  ARTIST_NOT_FOUND = 'Artist not found',
  USER_NOT_FOUND = 'User not found',
  INVALID_ARTIST_ROLE = 'Artist role is not valid',
  ACTIVE_COMMISSION_EXISTS = 'You already have an active commission request with this artist. Please complete or cancel it before starting a new one.',
  CONVERSATION_CREATION_FAILED = 'Failed to initialize communication channel',
  COMMISSION_NOT_FOUND = 'Commission not found',
  COMMISSION_NOT_IN_DISPUTE = 'Commission is not currently in dispute',
  DISPUTE_RESOLUTION_FAILED = 'Failed to resolve dispute. Please try again or contact support.',
  COMMISSION_NOT_IN_UPDATABLE_STATUS = 'Commission cannot be updated in its current status',
  FINAL_ARTWORK_REQUIRED = 'Final artwork is required for delivery',
  FUND_RELEASE_FAILED = 'Failed to release funds. Please try again or contact support.',
  USER_NOT_AUTHORIZED = 'User not authorized to perform this action',
  DISPUTE_CAN_ONLY_BE_RAISED_AFTER_DELIVERY_OR_DEADLINE = 'Dispute can only be raised after delivery or if deadline has passed',
  COMMISSION_NOT_IN_PROGRESS = 'Commission must be in progress to be delivered',
  COMMISSION_LIST_FETCH_SUCCESS = 'Commission list fetched successfully',
  COMMISSION_DISPUTE_RESOLVED = 'Commission dispute resolved successfully',
  COMMISSION_STATS_FETCH_SUCCESS = 'Commission stats fetched successfully',
  RECENT_COMMISSIONS_FETCH_SUCCESS = 'Recent commissions fetched successfully',
  COMMISSION_FETCH_SUCCESS = 'Commission details fetched successfully',
  UPDATE_SUCCESS = 'Commission updated successfully',
  REQUEST_SUCCESS = 'Commission request created successfully',

}
