export const API_ENDPOINTS = {
  AUTH_INITIALIZE: "/api/v1/auth/initialize",
  ART_ADMIN_AI_ANALYTICS: "/api/v1/art/admin/ai/analytics",
  ART_ADMIN_AI_CONFIG: "/api/v1/art/admin/ai/config",
  ART_ADMIN_AI_TESTPROVIDER: "/api/v1/art/admin/ai/test-provider",
  ART_ADMIN_ART: "/api/v1/art/admin/art",
  ART_ADMIN_AUCTIONS_1: "/api/v1/art/admin/auctions",
  ADMIN_LOGIN: "/api/v1/admin/login",
  ADMIN_LOGOUT: "/api/v1/admin/logout",
  ART_CATEGORY: "/api/v1/art/category",
  ADMIN_REPORTS_BULKSTATUS: "/api/v1/admin/reports/bulk-status",
  ART_ADMIN_AUCTIONS_STATS: "/api/v1/art/admin/auctions/stats",
  ART_ADMIN_COMMISSIONS_STATS: "/api/v1/art/admin/commissions/stats",
  ADMIN_DASHBOARDSTATS: "/api/v1/admin/dashboard-stats",
  WALLET_ADMIN_TRANSACTIONS_STATS: "/api/v1/wallet/admin/transactions/stats",
  ART_ADMIN_PLATFORMCONFIG: "/api/v1/art/admin/platform-config",
  ADMIN_USERS: "/api/v1/admin/users",
  WALLET_ADMIN_WALLETS: "/api/v1/wallet/admin/wallets",
  WALLET_ADMIN_WITHDRAWAL_REQUESTS_1: "/api/v1/wallet/admin/withdrawal/requests",
  WALLET_ADMIN_WITHDRAWAL_STATS: "/api/v1/wallet/admin/withdrawal/stats",
  ART_AI_QUOTA: "/api/v1/art/ai/quota",
  ART_AI_GENERATE: "/api/v1/art/ai/generate",
  ART_AI_CONFIG: "/api/v1/art/ai/config",
  USER_ARTISTREQUEST: "/api/v1/user/artist-request",
  ART_1: "/api/v1/art",
  ART_FAVORITE: "/api/v1/art/favorite",
  ART_CATEGORYSTATUSACTIVELIMIT100: "/api/v1/art/category?status=active&limit=100",
  USER_ARTISTREQUEST_STATUS: "/api/v1/user/artist-request/status",
  ART_LIKE: "/api/v1/art/like",
  ART_COMMENT_1: "/api/v1/art/comment/",
  ART_RECOMMENDED: "/api/v1/art/recommended",
  ART_UNFAVORITE: "/api/v1/art/unfavorite",
  ART_UNLIKE: "/api/v1/art/unlike",
  UPLOAD_ART: "/api/v1/upload/art",
  AUTH_FORGOTPASSWORD: "/api/v1/auth/forgot-password",
  AUTH_GOOGLEAUTH: "/api/v1/auth/google-auth",
  AUTH_LOGIN: "/api/v1/auth/login",
  AUTH_LOGOUT: "/api/v1/auth/logout",
  AUTH_RESETPASSWORD: "/api/v1/auth/reset-password",
  AUTH_STARTREGISTER: "/api/v1/auth/start-register",
  AUTH_REGISTER: "/api/v1/auth/register",
  ART_AUCTIONS_COUNTS: "/api/v1/art/auctions/counts",
  UPLOAD: "/api/v1/upload",
  ART_AUCTIONS_2: "/api/v1/art/auctions",
  ART_MYBIDDINGHISTORY: "/api/v1/art/my-bidding-history",
  ART_BIDS_1: "/api/v1/art/bids",
  CHAT_CONVERSATION_GROUP: "/api/v1/chat/conversation/group",
  CHAT_CONVERSATION_PRIVATE: "/api/v1/chat/conversation/private",
  USER_BATCH: "/api/v1/user/batch",
  ART_COMMISSION_CHECKONGOING: "/api/v1/art/commission/check-ongoing",
  WALLET_TRANSACTION_COMMISSION_LOCK: "/api/v1/wallet/transaction/commission/lock",
  ART_COMMISSION_REQUEST: "/api/v1/art/commission/request",
  UPLOAD_COMMISSION: "/api/v1/upload/commission",
  NOTIFICATIONS_MARKALLREAD: "/api/v1/notifications/mark-all-read",
  NOTIFICATIONS: "/api/v1/notifications",
  ART_PLATFORMCONFIG: "/api/v1/art/platform-config",
  UPLOAD_DELETE: "/api/v1/upload/delete",
  USER_PROFILE_1: "/api/v1/user/profile",
  UPLOAD_1: "/api/v1/upload/",
  USER_REPORT: "/api/v1/user/report",
  USER_CHANGEEMAIL: "/api/v1/user/change-email",
  USER_CHANGEPASSWORD: "/api/v1/user/change-password",
  USER_VERIFYEMAILTOKEN: "/api/v1/user/verify-email-token",
  AUTH_CHANGEPASSWORD: "/api/v1/auth/change-password",
  ART_SHOP: "/api/v1/art/shop",
  WALLET_RAZORPAY_CREATEORDER: "/api/v1/wallet/razorpay/create-order",
  WALLET_STRIPE_CREATECHECKOUTSESSION: "/api/v1/wallet/stripe/create-checkout-session",
  WALLET_WITHDRAWAL_CREATE: "/api/v1/wallet/withdrawal/create",
  WALLET_GETTRANSACTIONS: "/api/v1/wallet/get-transactions",
  WALLET_DETAILS: "/api/v1/wallet/details",
  WALLET_WITHDRAWAL_REQUESTS: "/api/v1/wallet/withdrawal/requests",
  WALLET_GIFT: "/api/v1/wallet/gift",
  ART_LIKE_LIKEDARTS: "/api/v1/art/like/liked-arts",
  ART_PURCHASEANALYTICS: "/api/v1/art/purchase-analytics",
  ART_PURCHASED: "/api/v1/art/purchased",
  ART_SALESANALYTICS: "/api/v1/art/sales-analytics",
  ART_SALED: "/api/v1/art/saled",
  ART_ADMIN_ART_1: (param1: string | number) => `/api/v1/art/admin/art/${param1}/status`,
  ART_ADMIN_AUCTIONS: (param1: string | number) => `/api/v1/art/admin/auctions/${param1}/cancel`,
  ART_BIDS: (param1: string | number) => `/api/v1/art/bids/${param1}`,
  ART_ADMIN_AUCTIONS_2: (param1: string | number) => `/api/v1/art/admin/auctions/${param1}`,
  ART_ADMIN_AUCTIONS_3: (param1: string | number) => `/api/v1/art/admin/auctions/${param1}/settle`,
  ART_CATEGORY_1: (param1: string | number) => `/api/v1/art/category/${param1}`,
  ADMIN_REPORTS: (param1: string | number) => `/api/v1/admin/reports?${param1}`,
  ADMIN_REPORTS_GROUPED: (param1: string | number) => `/api/v1/admin/reports/grouped?${param1}`,
  USER_PROFILEID: (param1: string | number) => `/api/v1/user/profile-id/${param1}`,
  ART: (param1: string | number) => `/api/v1/art/${param1}`,
  ART_COMMENT: (param1: string | number) => `/api/v1/art/comment/${param1}`,
  ADMIN_REPORTS_1: (param1: string | number) => `/api/v1/admin/reports/${param1}/status`,
  ADMIN_REVENUESTATSTIMERANGE: (param1: string | number) => `/api/v1/admin/revenue-stats?timeRange=${param1}`,
  ADMIN_ARTISTREQUEST: (param1: string | number) => `/api/v1/admin/artist-request/${param1}/approve`,
  ADMIN_GETARTISTREQUESTSPAGE: (param1: string | number, param2: string | number) => `/api/v1/admin/get-artist-requests?page=${param1}&limit=${param2}`,
  ADMIN_ARTISTREQUEST_1: (param1: string | number) => `/api/v1/admin/artist-request/${param1}/reject`,
  ADMIN_USERS_1: (param1: string | number) => `/api/v1/admin/users/${param1}/ban-toggle`,
  WALLET_ADMIN_WALLETS_1: (param1: string | number) => `/api/v1/wallet/admin/wallets/${param1}/transactions`,
  WALLET_ADMIN_WALLETS_2: (param1: string | number) => `/api/v1/wallet/admin/wallets/${param1}/status`,
  WALLET_ADMIN_WITHDRAWAL_REQUESTS: (param1: string | number) => `/api/v1/wallet/admin/withdrawal/requests/${param1}/status`,
  WALLET_ADMIN_WITHDRAWAL_REQUESTS_2: (param1: string | number) => `/api/v1/wallet/admin/withdrawal/requests/${param1}/status`,
  ART_AI_GENERATIONS: (param1: string | number) => `/api/v1/art/ai/generations/${param1}`,
  ART_AI_GENERATIONSPAGE: (param1: string | number, param2: string | number) => `/api/v1/art/ai/generations?page=${param1}&limit=${param2}`,
  ART_BUY: (param1: string | number) => `/api/v1/art/buy/${param1}`,
  ART_2: (param1: string | number) => `/api/v1/art/${param1}`,
  ART_COMMENTS: (param1: string | number) => `/api/v1/art/comments/${param1}`,
  ART_DOWNLOAD: (param1: string | number) => `/api/v1/art/download/${param1}`,
  ART_COMMENTS_1: (param1: string | number) => `/api/v1/art/comments/${param1}`,
  ART_BYNAME: (param1: string | number) => `/api/v1/art/by-name/${param1}`,
  ART_COMMENTS_2: (param1: string | number) => `/api/v1/art/comments/${param1}`,
  ART_FAVORITES: (param1: string | number, param2: string | number) => `/api/v1/art/favorites/${param1}?page=${param2}&limit=5`,
  ART_LIKES: (param1: string | number, param2: string | number) => `/api/v1/art/likes/${param1}?page=${param2}&limit=5`,
  ART_3: (param1: string | number) => `/api/v1/art/${param1}`,
  ART_AUCTIONS: (param1: string | number) => `/api/v1/art/auctions/${param1}`,
  ART_AUCTIONS_1: (param1: string | number) => `/api/v1/art/auctions?${param1}`,
  ART_USER: (param1: string | number) => `/api/v1/art/user/${param1}`,
  CHAT_CONVERSATION: (param1: string | number, param2: string | number) => `/api/v1/chat/conversation/${param1}/member/${param2}`,
  CHAT_CONVERSATION_1: (param1: string | number, param2: string | number) => `/api/v1/chat/conversation/${param1}/admin/${param2}`,
  CHAT_CONVERSATION_2: (param1: string | number, param2: string | number) => `/api/v1/chat/conversation/${param1}/admin/${param2}`,
  CHAT_CONVERSATION_3: (param1: string | number, param2: string | number) => `/api/v1/chat/conversation/${param1}/member/${param2}`,
  CHAT_CONVERSATION_4: (param1: string | number, param2: string | number) => `/api/v1/chat/conversation/${param1}/members?page=${param2}&limit=20`,
  CHAT_MESSAGE: (param1: string | number, param2: string | number) => `/api/v1/chat/message/${param1}?limit=10&fromId=${param2}`,
  CHAT_MESSAGE_1: (param1: string | number) => `/api/v1/chat/message/${param1}?limit=10`,
  CHAT_CONVERSATION_RECENTPAGE: (param1: string | number) => `/api/v1/chat/conversation/recent?page=${param1}`,
  ART_COMMISSION_CONVERSATION: (param1: string | number) => `/api/v1/art/commission/conversation/${param1}`,
  ART_COMMISSION: (param1: string | number) => `/api/v1/art/commission/${param1}`,
  USER: (param1: string | number) => `/api/v1/user/${param1}/supporters`,
  USER_1: (param1: string | number) => `/api/v1/user/${param1}/supporting`,
  USER_PROFILE: (param1: string | number) => `/api/v1/user/profile/${param1}`,
  USER_2: (param1: string | number, param2: string | number) => `/api/v1/user/${param1}/supporters/${param2}`,
  USER_REMOVE: (param1: string | number) => `/api/v1/user/remove/${param1}`,
  USER_SUPPORT: (param1: string | number) => `/api/v1/user/support/${param1}`,
  USER_UNSUPPORT: (param1: string | number) => `/api/v1/user/un-support/${param1}`,
  ELASTIC_SEARCHQ: (param1: string | number, param2: string | number) => `/api/v1/elastic/search?q=${param1}&type=${param2}`,
  ART_SHOP_1: (param1: string | number) => `/api/v1/art/shop/${param1}`,
  WALLET_STATS_CHARTTIMERANGE: (param1: string | number) => `/api/v1/wallet/stats/chart?timeRange=${param1}`,
  WALLET_STRIPE_SESSION: (param1: string | number) => `/api/v1/wallet/stripe/session/${param1}`,
  CHAT_MESSAGE_2: (param1: string | number) => `/api/v1/chat/message/${param1}`,
  ART_FAVORITES_USER: (param1: string | number) => `/api/v1/art/favorites/user/${param1}`,
  ART_USER_1: (param1: string | number) => `/api/v1/art/user/${param1}`,
} as const;
