import React from 'react'

const GalleryTab:React.FC = () => {
  return (
    <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Architecto laboriosam quod, quo quibusdam asperiores quas delectus! Deleniti voluptate ipsum dolore expedita accusamus! Suscipit perspiciatis voluptatum culpa accusantium quisquam. Consectetur, unde?
    Temporibus molestias esse ipsam quisquam, tenetur quidem impedit neque accusantium eaque! Ab libero accusamus expedita illum modi. Suscipit, veritatis nam ullam eius fuga consequatur distinctio modi quis saepe iste neque!
    Deserunt ipsa eos vel, dolore laboriosam, quaerat sequi quos rem culpa eaque velit. Sequi obcaecati voluptatum est aliquam quod nostrum? Vero at nisi voluptas laudantium explicabo suscipit iusto ex repudiandae.
    Laudantium ex voluptates vel? Rem provident eius repudiandae voluptatibus dolorum, repellat quam earum nostrum dolores corrupti perspiciatis quaerat totam enim officia quas ea veniam nulla in quidem corporis minima tempore.
    Ipsam unde ad explicabo itaque corporis, corrupti dignissimos facilis dolorum, dolorem vel architecto ea atque, ex inventore quam officia in nemo hic illo recusandae ratione. Delectus deserunt repellendus ipsum illo.
    Mollitia cum libero aliquam magnam temporibus, quae eveniet laboriosam ducimus. Optio ullam voluptatibus velit. Nisi nulla odit ipsum culpa, blanditiis quae sint, error itaque voluptas deleniti tenetur ad saepe quos.
    Temporibus ipsa excepturi sed voluptatem voluptas eos esse voluptates! Nostrum facere maiores accusamus beatae, recusandae consequuntur aperiam tempore veritatis esse debitis, aut consectetur, nulla accusantium dolorum soluta libero quod exercitationem!
    Soluta, pariatur placeat iusto accusantium voluptatem ipsum debitis! Totam nam facere nesciunt rerum. Corporis ab officia dolorem enim explicabo ipsam unde, saepe quos maiores hic eligendi voluptatibus, at harum architecto.
    Ipsa aliquid libero illo, debitis in nesciunt! Quasi nulla quas maxime soluta? Consequatur vero harum ipsam doloribus fugiat distinctio facilis provident porro nam, rem excepturi cum. Eum aperiam ab aliquid.
    Assumenda ut officiis odit culpa, accusantium repellat esse aut sint, recusandae nisi ipsum? Sed recusandae laboriosam vero earum consequatur, similique natus molestias placeat nostrum expedita omnis, eius nulla tempore possimus.
    Mollitia, neque odio sunt alias aperiam blanditiis deleniti quaerat incidunt sed asperiores, non quos! Provident temporibus inventore voluptate ducimus. Consequatur, incidunt? Corrupti sunt doloribus illum ea iusto quasi autem perferendis?
    Fugiat quas vitae aut facere aliquid earum excepturi iste fuga veniam. Delectus est deserunt repudiandae, nihil enim voluptas similique! Aut esse praesentium nostrum fugit velit accusamus eos quis illo a!
    Necessitatibus facilis laboriosam veritatis? Voluptatibus ratione numquam dolor ut possimus voluptas minima reprehenderit libero laboriosam error, ullam amet tempora, unde dolorem quae voluptatum quam? In explicabo provident doloribus saepe voluptas!
    Sit expedita fugit aut cupiditate doloremque? Quod aliquam necessitatibus exercitationem repellendus ex inventore saepe consequatur perferendis, dolores dolor officia iure beatae ea quae qui accusantium itaque molestiae blanditiis sunt recusandae.
    Dicta a eos sint quos libero in sed vitae? Neque est consequatur tempore, perferendis autem fugit architecto blanditiis odio corrupti esse accusantium iusto voluptatibus modi cumque quam quae deleniti voluptate.
    Atque repellat minima quo saepe perferendis? Deserunt nulla in reiciendis dolorum impedit numquam architecto, nihil dolor quod natus laborum soluta consequuntur! Dolor totam magni modi explicabo fugiat cum qui error.
    Aliquid molestias vero voluptatibus, fugit in nihil minima ratione cum iste deserunt delectus dolores dolorem neque placeat laboriosam? Et, incidunt eligendi veniam eum fuga suscipit voluptatum soluta culpa totam nisi?
    Dolor recusandae accusamus ipsa totam voluptatem sapiente sequi, ea explicabo! Aut at eos fugiat enim quod, eligendi animi dicta provident maiores deleniti magni, suscipit inventore, totam cupiditate officiis natus aperiam.
    Temporibus ipsa ab reprehenderit voluptatem! Est delectus eligendi et tenetur placeat illo fuga aliquam autem odio quasi soluta quas ad vitae, facere hic officiis, at, deserunt assumenda inventore quaerat itaque?
    At ipsa minima illo illum. Esse saepe odit vel accusantium illo dicta dolorem, omnis corrupti nobis perferendis nihil! Et, accusamus. Similique provident voluptatibus consequuntur eum iure omnis aperiam consequatur hic?
    Sequi hic, totam autem sit neque nesciunt, in eaque iusto, vero pariatur dolores cupiditate voluptatibus dolor? Libero quaerat fugit nihil dicta culpa. Reiciendis dolores nostrum fugit repellendus aliquid dolorem ipsa.
    Recusandae quasi animi nobis consequuntur reprehenderit dicta at accusantium ducimus voluptate sequi maiores laboriosam, aspernatur dolore, molestias quaerat et! Molestias praesentium facere reiciendis odio ipsa sequi nam, provident eligendi et.
    Ratione voluptatem cum vitae incidunt accusamus officia accusantium explicabo hic. Officia assumenda id aliquam quod nesciunt recusandae enim fugit, nulla suscipit vel, harum, deserunt odit velit. Accusantium doloremque saepe velit.
    Repellendus natus nisi earum quia neque culpa voluptas veritatis sit commodi, eaque corporis mollitia. Doloribus delectus enim quos? Assumenda, voluptatem. Tempora amet rerum at illo placeat harum ipsa, velit quibusdam?
    Fuga, fugiat laudantium? Perferendis iste vitae sit animi deserunt reiciendis tempore, repellat eum repellendus omnis. A amet laudantium commodi obcaecati, saepe placeat doloribus culpa quasi ea, sint hic perspiciatis asperiores!
    Voluptatum itaque blanditiis animi qui quisquam rerum doloremque iure temporibus. Quasi nulla dolores fugit saepe omnis quidem cupiditate nesciunt architecto laudantium nam sed, eum velit doloremque ea expedita nobis rem?
    Ducimus laborum eius reiciendis tenetur perferendis harum. Recusandae distinctio eos officiis a adipisci animi quisquam ab qui numquam amet, quidem officia dolorem saepe quae id tempore ratione neque similique eveniet.
    Id voluptas molestias nostrum quidem incidunt, odio perspiciatis velit dolorum repudiandae inventore! Ipsa, commodi delectus aliquid quos deserunt voluptatibus nesciunt pariatur similique natus saepe? Fuga expedita laborum officia dignissimos tempore?
    Sint voluptas consectetur eius ipsam ducimus fugit qui ullam, delectus sit, earum aliquid numquam minima vero repudiandae fuga eaque accusamus nisi facere iure nam aspernatur eum nihil quae obcaecati! Ad!
    Nesciunt possimus deserunt reprehenderit repudiandae quos voluptatibus dolorum earum architecto explicabo cumque inventore officia id, libero velit recusandae sit et eius ducimus, dicta quas neque! Eum quidem eligendi saepe voluptatum?
    Perspiciatis fugit expedita assumenda? Ipsa tempora cupiditate reiciendis fugiat. Tempore aperiam autem alias nam laboriosam similique nobis doloribus perspiciatis nesciunt aliquam commodi assumenda architecto, eveniet minus. Maiores animi eveniet harum.
    Eveniet placeat amet ratione fugiat, quidem accusamus. Officia quo error aliquam quis expedita obcaecati explicabo! Accusantium, necessitatibus rem. Aut a provident optio ipsum in eligendi velit temporibus corrupti culpa vero?
    Quae ipsa sunt distinctio eveniet reiciendis deleniti mollitia, quas debitis voluptas aspernatur a illo soluta quisquam! Illo quidem omnis beatae, at nihil molestias explicabo ad eveniet totam quibusdam quos earum?
    Quis porro facere accusantium ratione esse. Obcaecati, sequi? Ratione dolorum a laudantium temporibus quidem! Molestiae saepe magnam ullam aliquid deleniti voluptatibus id animi eos. Quod doloremque repellendus culpa ipsam fuga!
    Eos, aliquam! Rerum quia ad commodi, exercitationem nam libero, eius perspiciatis placeat, praesentium nobis quo? Laborum, ipsum. Deserunt, beatae veritatis? Corrupti tempore laborum quod perspiciatis harum eum, quaerat et sunt!
    Dolores voluptatum facilis totam eaque nulla non beatae nisi sapiente eos? Magni suscipit perspiciatis possimus sed quia hic animi perferendis laborum exercitationem tempora adipisci eveniet ullam saepe, ipsam pariatur totam.
    Reiciendis libero officiis sed, amet non repudiandae ipsum pariatur, id voluptatibus obcaecati quia ex itaque mollitia dolorum incidunt accusamus illum iure! Molestias alias, earum neque saepe error iure autem ea.
    Possimus provident consequatur porro accusamus praesentium labore nobis aut voluptatum, aspernatur, nam dolores quo facilis perferendis natus sed! Culpa eligendi nam in sunt, quam enim quas obcaecati quae quod ad!
    Nemo nulla distinctio atque eos neque doloremque eius esse, dolor expedita facilis placeat iste necessitatibus beatae iusto magnam dolorem aperiam ducimus obcaecati mollitia consectetur, nesciunt corporis, consequuntur recusandae. Dolore, dolores!
    Delectus error in natus. Modi eos non sunt ut possimus. Eos ipsam aspernatur fugiat quod, soluta sint, corrupti sed inventore amet perspiciatis consectetur harum quia quas quae veritatis, mollitia dolore!
    Consectetur, reprehenderit assumenda! Maiores maxime, alias quidem modi voluptatum vitae, animi atque dicta facere sequi quia ipsam fugiat numquam consequatur incidunt sed illo, quisquam inventore veniam deserunt deleniti reprehenderit! Commodi.
    Dolorum vitae laboriosam provident quia minima commodi, cum voluptas corporis et id aut facilis at quaerat totam ducimus. Minima reprehenderit eius repudiandae similique corporis blanditiis repellendus aspernatur at aperiam veritatis?
    Molestiae, explicabo, excepturi hic expedita et facilis non ducimus voluptatibus saepe cupiditate aperiam! Eveniet necessitatibus, voluptas exercitationem, aperiam quibusdam illo reiciendis voluptates velit soluta earum doloremque amet nam. Quam, earum.
    Soluta delectus, rerum commodi sed mollitia perferendis accusamus consequuntur in. Possimus ipsam, quo porro inventore provident officiis nihil accusantium vero, nemo nulla excepturi cum enim reprehenderit fugit unde eaque at!
    Blanditiis perspiciatis consectetur voluptatem quas itaque, illo est dolorum voluptatum. Expedita soluta, laboriosam optio commodi ex tenetur adipisci atque maiores ipsum culpa debitis eius dignissimos, doloribus accusamus eos magnam distinctio.</div>
  )
}

export default GalleryTab