// data/dummyData.ts
import {
  type Conversation,
  ConversationType,
  type Message,
  DeleteMode,
  MediaType,
  type User,
} from "../../../../types/chat/chat";

export const dummyUsers: User[] = [
  { id: "1", name: "You", username: "you", isOnline: true },
  {
    id: "2",
    name: "John Doe",
    username: "johndoe",
    isOnline: true,
    lastSeen: new Date(),
  },
  {
    id: "3",
    name: "Sarah Wilson",
    username: "sarahw",
    isOnline: true,
    lastSeen: new Date(),
  },
  {
    id: "4",
    name: "Mike Johnson",
    username: "mikej",
    isOnline: false,
    lastSeen: new Date(Date.now() - 3600000),
  },
  {
    id: "5",
    name: "Alex Brown",
    username: "alexb",
    isOnline: false,
    lastSeen: new Date(Date.now() - 86400000),
  },
  {
    id: "6",
    name: "Emma Davis",
    username: "emmad",
    isOnline: true,
    lastSeen: new Date(),
  },
  {
    id: "7",
    name: "David Miller",
    username: "davidm",
    isOnline: false,
    lastSeen: new Date(Date.now() - 7200000),
  },
  {
    id: "8",
    name: "Lisa Taylor",
    username: "lisat",
    isOnline: true,
    lastSeen: new Date(),
  },
  {
    id: "9",
    name: "Robert Wilson",
    username: "robertw",
    isOnline: true,
    lastSeen: new Date(),
  },
  {
    id: "10",
    name: "Maria Garcia",
    username: "mariag",
    isOnline: false,
    lastSeen: new Date(Date.now() - 172800000),
  },
];

export const dummyConversations: Conversation[] = [
  {
    id: "1",
    type: ConversationType.PRIVATE,
    name: "John Doe",
    memberIds: ["1", "2"],
    members: [dummyUsers[0], dummyUsers[1]],
    lastMessage: "Hey, how are you doing?",
    lastMessageTime: "2m",
    unreadCount: 2,
    isOnline: true,
    lastSeen: "2 min ago",
    locked: false,
  },
  {
    id: "2",
    type: ConversationType.PRIVATE,
    name: "Sarah Wilson",
    memberIds: ["1", "3"],
    members: [dummyUsers[0], dummyUsers[2]],
    lastMessage: "See you tomorrow!",
    lastMessageTime: "1h",
    unreadCount: 0,
    isOnline: true,
    lastSeen: "1 hour ago",
    locked: false,
  },
  {
    id: "3",
    type: ConversationType.GROUP,
    name: "Design Team",
    memberIds: ["1", "2", "3", "4"],
    members: [dummyUsers[0], dummyUsers[1], dummyUsers[2], dummyUsers[3]],
    adminIds: ["1"],
    lastMessage: "Mike: The design looks great!",
    lastMessageTime: "3h",
    unreadCount: 5,
    isOnline: true,
    lastSeen: "3 hours ago",
    description: "Team collaboration for design projects",
    locked: false,
  },
  {
    id: "4",
    type: ConversationType.PRIVATE,
    name: "Alex Brown",
    memberIds: ["1", "5"],
    members: [dummyUsers[0], dummyUsers[4]],
    lastMessage: "Hi there!",
    lastMessageTime: "1d",
    unreadCount: 0,
    isOnline: false,
    lastSeen: "2 days ago",
    locked: true,
  },
  {
    id: "5",
    type: ConversationType.GROUP,
    name: "Development",
    memberIds: ["1", "2", "6"],
    members: [dummyUsers[0], dummyUsers[1], dummyUsers[5]],
    adminIds: ["1", "2"],
    lastMessage: "John: Let's meet tomorrow",
    lastMessageTime: "5h",
    unreadCount: 3,
    isOnline: true,
    lastSeen: "5 hours ago",
    description: "Development team chat",
    locked: false,
  },
  {
    id: "6",
    type: ConversationType.PRIVATE,
    name: "Emma Davis",
    memberIds: ["1", "6"],
    members: [dummyUsers[0], dummyUsers[5]],
    lastMessage: "Can you review the PR?",
    lastMessageTime: "30m",
    unreadCount: 1,
    isOnline: true,
    lastSeen: "30 min ago",
    locked: false,
  },
  {
    id: "7",
    type: ConversationType.GROUP,
    name: "Marketing Team",
    memberIds: ["1", "3", "7", "8"],
    members: [dummyUsers[0], dummyUsers[2], dummyUsers[6], dummyUsers[7]],
    adminIds: ["1", "3"],
    lastMessage: "Lisa: Campaign results are in!",
    lastMessageTime: "2h",
    unreadCount: 7,
    isOnline: true,
    lastSeen: "2 hours ago",
    description: "Marketing campaign discussions",
    locked: false,
  },
  {
    id: "8",
    type: ConversationType.PRIVATE,
    name: "David Miller",
    memberIds: ["1", "7"],
    members: [dummyUsers[0], dummyUsers[6]],
    lastMessage: "Thanks for your help!",
    lastMessageTime: "1d",
    unreadCount: 0,
    isOnline: false,
    lastSeen: "1 day ago",
    locked: false,
  },
  {
    id: "9",
    type: ConversationType.GROUP,
    name: "Friends Circle",
    memberIds: ["1", "2", "3", "6", "8"],
    members: [
      dummyUsers[0],
      dummyUsers[1],
      dummyUsers[2],
      dummyUsers[5],
      dummyUsers[7],
    ],
    adminIds: ["1"],
    lastMessage: "Sarah: Party at my place this weekend!",
    lastMessageTime: "4h",
    unreadCount: 12,
    isOnline: true,
    lastSeen: "4 hours ago",
    description: "Friend group chat",
    locked: false,
  },
  {
    id: "10",
    type: ConversationType.PRIVATE,
    name: "Robert Wilson",
    memberIds: ["1", "9"],
    members: [dummyUsers[0], dummyUsers[8]],
    lastMessage: "Meeting postponed",
    lastMessageTime: "45m",
    unreadCount: 0,
    isOnline: true,
    lastSeen: "45 min ago",
    locked: false,
  },
  {
    id: "11",
    type: ConversationType.PRIVATE,
    name: "Maria Garcia",
    memberIds: ["1", "10"],
    members: [dummyUsers[0], dummyUsers[9]],
    lastMessage: "Hello!",
    lastMessageTime: "3d",
    unreadCount: 0,
    isOnline: false,
    lastSeen: "3 days ago",
    locked: true,
  },
  {
    id: "12",
    type: ConversationType.GROUP,
    name: "Project Alpha",
    memberIds: ["1", "4", "7", "9"],
    members: [dummyUsers[0], dummyUsers[3], dummyUsers[6], dummyUsers[8]],
    adminIds: ["1", "9"],
    lastMessage: "Robert: Deadline extended",
    lastMessageTime: "6h",
    unreadCount: 4,
    isOnline: false,
    lastSeen: "6 hours ago",
    description: "Project Alpha team coordination",
    locked: false,
  },
];

export const dummyMessages: Message[] = [
  // Conversation 1 messages
  {
    id: "1",
    conversationId: "1",
    senderId: "2",
    sender: dummyUsers[1],
    content: "Hey! How's it going? 👋",
    readBy: ["1"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(Date.now() - 3600000),
  },
  {
    id: "2",
    conversationId: "1",
    senderId: "1",
    sender: dummyUsers[0],
    content: "I'm good! Just working on some new designs 🎨",
    readBy: ["2"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 3500000),
    updatedAt: new Date(Date.now() - 3500000),
  },
  {
    id: "3",
    conversationId: "1",
    senderId: "2",
    sender: dummyUsers[1],
    content: "That's awesome! Can you share some screenshots?",
    readBy: ["1"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 3400000),
    updatedAt: new Date(Date.now() - 3400000),
  },
  {
    id: "4",
    conversationId: "1",
    senderId: "1",
    sender: dummyUsers[0],
    content: "Sure, I'll send them over in a bit",
    readBy: ["2"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 3300000),
    updatedAt: new Date(Date.now() - 3300000),
  },
  {
    id: "5",
    conversationId: "1",
    senderId: "2",
    sender: dummyUsers[1],
    content: "Great, looking forward to it!",
    readBy: ["1"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 3200000),
    updatedAt: new Date(Date.now() - 3200000),
  },

  // Conversation 2 messages
  {
    id: "6",
    conversationId: "2",
    senderId: "3",
    sender: dummyUsers[2],
    content: "Hey! Are we still meeting tomorrow?",
    readBy: ["1"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 7200000),
    updatedAt: new Date(Date.now() - 7200000),
  },
  {
    id: "7",
    conversationId: "2",
    senderId: "1",
    sender: dummyUsers[0],
    content: "Yes, 2 PM at the usual place",
    readBy: ["3"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 7100000),
    updatedAt: new Date(Date.now() - 7100000),
  },
  {
    id: "8",
    conversationId: "2",
    senderId: "3",
    sender: dummyUsers[2],
    content: "Perfect! See you then 👋",
    readBy: ["1"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 7000000),
    updatedAt: new Date(Date.now() - 7000000),
  },

  // Conversation 3 messages (Group)
  {
    id: "9",
    conversationId: "3",
    senderId: "4",
    sender: dummyUsers[3],
    content: "The design looks great!",
    readBy: ["1", "2"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 10800000),
    updatedAt: new Date(Date.now() - 10800000),
  },
  {
    id: "10",
    conversationId: "3",
    senderId: "1",
    sender: dummyUsers[0],
    content: "Thanks Mike! I'll share the final version tomorrow",
    readBy: ["2", "3", "4"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 10600000),
    updatedAt: new Date(Date.now() - 10600000),
  },
  {
    id: "11",
    conversationId: "3",
    senderId: "2",
    sender: dummyUsers[1],
    content: "Can't wait to see it!",
    readBy: ["1", "3", "4"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 10400000),
    updatedAt: new Date(Date.now() - 10400000),
  },
  {
    id: "12",
    conversationId: "3",
    senderId: "3",
    sender: dummyUsers[2],
    content: "The color scheme is perfect for our brand",
    readBy: ["1", "2", "4"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 10200000),
    updatedAt: new Date(Date.now() - 10200000),
  },

  // Conversation 4 messages (Locked/Request)
  {
    id: "13",
    conversationId: "4",
    senderId: "5",
    sender: dummyUsers[4],
    content: "Hi there!",
    readBy: ["1"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 86400000),
  },

  // Conversation 5 messages (Group)
  {
    id: "14",
    conversationId: "5",
    senderId: "2",
    sender: dummyUsers[1],
    content: "Let's meet tomorrow to discuss the new features",
    readBy: ["1", "6"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 18000000),
    updatedAt: new Date(Date.now() - 18000000),
  },
  {
    id: "15",
    conversationId: "5",
    senderId: "1",
    sender: dummyUsers[0],
    content: "What time works for everyone?",
    readBy: ["2", "6"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 17600000),
    updatedAt: new Date(Date.now() - 17600000),
  },
  {
    id: "16",
    conversationId: "5",
    senderId: "6",
    sender: dummyUsers[5],
    content: "I'm free after 3 PM",
    readBy: ["1", "2"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 17200000),
    updatedAt: new Date(Date.now() - 17200000),
  },

  // Conversation 6 messages
  {
    id: "17",
    conversationId: "6",
    senderId: "6",
    sender: dummyUsers[5],
    content: "Can you review the PR when you get a chance?",
    readBy: ["1"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 1800000),
    updatedAt: new Date(Date.now() - 1800000),
  },
  {
    id: "18",
    conversationId: "6",
    senderId: "1",
    sender: dummyUsers[0],
    content: "Sure, I'll take a look now",
    readBy: ["6"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 1200000),
    updatedAt: new Date(Date.now() - 1200000),
  },

  // Conversation 7 messages (Group)
  {
    id: "19",
    conversationId: "7",
    senderId: "8",
    sender: dummyUsers[7],
    content: "Campaign results are in! We exceeded our targets by 25%! 🎉",
    readBy: ["1", "3"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 7200000),
    updatedAt: new Date(Date.now() - 7200000),
  },
  {
    id: "20",
    conversationId: "7",
    senderId: "3",
    sender: dummyUsers[2],
    content: "That's amazing news! Great work everyone!",
    readBy: ["1", "7", "8"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 7100000),
    updatedAt: new Date(Date.now() - 7100000),
  },
  {
    id: "21",
    conversationId: "7",
    senderId: "7",
    sender: dummyUsers[6],
    content: "The social media ads performed really well",
    readBy: ["1", "3", "8"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 7000000),
    updatedAt: new Date(Date.now() - 7000000),
  },

  // Conversation 9 messages (Group - Friends)
  {
    id: "22",
    conversationId: "9",
    senderId: "3",
    sender: dummyUsers[2],
    content: "Party at my place this weekend! Saturday 7 PM 🎊",
    readBy: ["1", "2", "6"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 14400000),
    updatedAt: new Date(Date.now() - 14400000),
  },
  {
    id: "23",
    conversationId: "9",
    senderId: "2",
    sender: dummyUsers[1],
    content: "Count me in! Should I bring anything?",
    readBy: ["1", "3", "6", "8"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 14200000),
    updatedAt: new Date(Date.now() - 14200000),
  },
  {
    id: "24",
    conversationId: "9",
    senderId: "6",
    sender: dummyUsers[5],
    content: "I'll bring drinks! 🍻",
    readBy: ["1", "2", "3", "8"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 14000000),
    updatedAt: new Date(Date.now() - 14000000),
  },
  {
    id: "25",
    conversationId: "9",
    senderId: "8",
    sender: dummyUsers[7],
    content: "Can't wait! It's been too long since we all hung out",
    readBy: ["1", "2", "3", "6"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 13800000),
    updatedAt: new Date(Date.now() - 13800000),
  },

  // Conversation 10 messages
  {
    id: "26",
    conversationId: "10",
    senderId: "9",
    sender: dummyUsers[8],
    content: "The meeting has been postponed to next week",
    readBy: ["1"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 2700000),
    updatedAt: new Date(Date.now() - 2700000),
  },
  {
    id: "27",
    conversationId: "10",
    senderId: "1",
    sender: dummyUsers[0],
    content: "Thanks for letting me know. Same time?",
    readBy: ["9"],
    deleteMode: DeleteMode.ME,
    createdAt: new Date(Date.now() - 2600000),
    updatedAt: new Date(Date.now() - 2600000),
  },

  // Conversation 12 messages (Group)
  {
    id: "28",
    conversationId: "12",
    senderId: "9",
    sender: dummyUsers[8],
    content: "Good news everyone - the deadline has been extended by one week",
    readBy: ["1", "4", "7"],
    deleteMode: DeleteMode.NONE,
    createdAt: new Date(Date.now() - 21600000),
    updatedAt: new Date(Date.now() - 21600000),
  },
  {
    id: "29",
    conversationId: "12",
    senderId: "4",
    sender: dummyUsers[3],
    content: "That's a relief! I was getting worried about the timeline",
    readBy: ["1", "7", "9"],
    deleteMode: DeleteMode.ALL,
    createdAt: new Date(Date.now() - 21500000),
    updatedAt: new Date(Date.now() - 21500000),
  },
  {
    id: "30",
    conversationId: "12",
    senderId: "7",
    sender: dummyUsers[6],
    content: "Perfect, this gives us more time for testing",
    readBy: ["1", "4", "9"],
    deleteMode: DeleteMode.ALL,
    createdAt: new Date(Date.now() - 21400000),
    updatedAt: new Date(Date.now() - 21400000),
  },

];
